version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "1.0"
    #command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    #runtime: nvidia # Use this if you're enabling GPU support
